[Config]
Dependencies=initrd

[Distribution]
Distribution=ubuntu
Release=resolute
Repositories=main restricted universe multiverse

[Output]
Format=disk
Output=tinfoilcvm

[Content]
Hostname=tinfoil
Bootable=yes
Initrds=initrd
PackageDirectories=packages
RootPassword=!
Bootloader=systemd-boot
KernelModulesInitrdExclude=.*
KernelModulesInitrdInclude=
    default
    virtio
    scsi
    sd_mod
    dm-mod
    dm-verity
    dm-crypt
    dm-bufio
    ext4
    vfat
    nls_
    sha256
    sha512
    aes
    gcm
    ecdh
    ecdsa
    crct10dif
    crc32
    loop
    overlay
    tdx_guest
Packages=
    systemd
    systemd-boot
    ubuntu-standard
    build-essential
    kmod
    procps
    iputils-ping
    curl
    iproute2
    nano
    systemd-resolved
    ca-certificates
    nftables
    cryptsetup
    systemd-cryptsetup
    udev
    linux-generic
    linux-headers-generic
    nvidia-driver-open=595.71.05-1ubuntu1
    nvidia-persistenced=595.71.05-1ubuntu1
    nvidia-fabricmanager=595.71.05-1ubuntu1
    libnvidia-nscq=595.71.05-1ubuntu1
    nvattest=1.2.0.1772475102-1
    nvidia-container-toolkit=1.19.0-1
    docker-ce=5:29.4.2-2~ubuntu.26.04~resolute
    docker-ce-cli=5:29.4.2-2~ubuntu.26.04~resolute
    containerd.io=2.2.3-1~ubuntu.26.04~resolute

[Build]
ToolsTree=default
ToolsTreeDistribution=ubuntu
ToolsTreeRelease=resolute
WithNetwork=yes
Incremental=yes
